package com.hmg.role.admin.member;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.hmg.role.CucumberSpringConfiguration;
import io.cucumber.docstring.DocString;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import java.util.HashMap;
import java.util.Map;
import org.junit.platform.commons.util.StringUtils;

public class CreateMemberStepDefinitionTest extends CucumberSpringConfiguration {

    @Given("HMG Role Admin wants to create a new Member with the following attributes")
    public void
            theHMGRoleAdminWantsToCreateANewMemberForTheProjectHmgNoticeWithTheFollowingAttributes(
                    DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @When("the HMG Role Admin creates a new Member")
    public void theHMGRoleAdminCreatesANewMember() throws Exception {
        createMember();
    }

    @Then("the Member is created successfully with response code {int}")
    public void theMemberIsCreatedSuccessfullyWithResponseCode(int expectedResponseCode) {
        assertThat(scenarioContext.getContext("responseCode")).isEqualTo(expectedResponseCode);
    }

    @And("return the created Member")
    public void returnTheCreatedMember(DocString expectedResponseBody) throws Exception {
        var expectedResponseMap =
                mapper.readValue(expectedResponseBody.getContent(), HashMap.class);
        var result = (Map) scenarioContext.getContext("results");

        assertThat(result.get("key")).isEqualTo(expectedResponseMap.get("key"));
        assertThat(result.get("name")).isEqualTo(expectedResponseMap.get("name"));
        assertThat(result.get("apiKey")).isEqualTo(expectedResponseMap.get("apiKey"));
    }

    @And("return the created Member with an auto generated UUID")
    public void returnTheCreatedMemberWithAutoGeneratedUUID(DocString expectedResponseBody)
            throws Exception {
        var expectedResponseMap =
                mapper.readValue(expectedResponseBody.getContent(), HashMap.class);
        var result = (Map) scenarioContext.getContext("results");

        assertThat(result.get("key")).isEqualTo(expectedResponseMap.get("key"));
        assertThat(result.get("name")).isEqualTo(expectedResponseMap.get("name"));
        assertTrue(
                result.get("apiKey")
                        .toString()
                        .matches(
                                "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"));
    }

    @Given("HMG Role Admin wants to create a new Member with an empty key")
    public void hmgRoleAdminWantsToCreateANewMemberWithAnEmptyKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Then("the Member creation fails with response code {int}")
    public void theMemberCreationFailsWithResponseCode(int expectedResponseCode) {
        assertThat(scenarioContext.getContext("responseCode")).isEqualTo(expectedResponseCode);
    }

    @Given("HMG Role Admin wants to create a new Member with a null key")
    public void hmgRoleAdminWantsToCreateANewMemberWithANullKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with a blank key")
    public void hmgRoleAdminWantsToCreateANewMemberWithABlankKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with an empty name")
    public void hmgRoleAdminWantsToCreateANewMemberWithAnEmptyName(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with a null name")
    public void hmgRoleAdminWantsToCreateANewMemberWithANullName(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with a blank name")
    public void hmgRoleAdminWantsToCreateANewMemberWithABlankName(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member without apiKey")
    public void hmgRoleAdminWantsToCreateANewMemberWithoutApiKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with an empty apiKey")
    public void hmgRoleAdminWantsToCreateANewMemberWithAnEmptyApiKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with a null apiKey")
    public void hmgRoleAdminWantsToCreateANewMemberWithANullApiKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("HMG Role Admin wants to create a new Member with a blank apiKey")
    public void hmgRoleAdminWantsToCreateANewMemberWithABlankApiKey(DocString request) {
        scenarioContext.setContext("requestContent", request.getContent());
    }

    @Given("an existing Member as the following attributes")
    public void anExistingMemberAsTheFollowingAttributes(DocString request) throws Exception {
        scenarioContext.setContext("requestContent", request.getContent());
        createMember();
    }

    @When("the HMG Role Admin creates a new Member with an existing or duplicate key")
    public void theHMGRoleAdminCreatesANewMemberWithAnExistingOrDuplicateKey() {
        createMember();
    }

    @When("the HMG Role Admin creates a new Member with an existing or duplicate apiKey")
    public void theHMGRoleAdminCreatesANewMemberWithAnExistingOrDuplicateApiKey() {
        createMember();
    }

    private void createMember() {
        var apiKey = scenarioContext.getContext("apiKeyProjectAdmin");
        var projectKey = scenarioContext.getContext("projectKey");
        Response response =
                request()
                        .log()
                        .all()
                        .contentType(ContentType.JSON)
                        .body(scenarioContext.getContext("requestContent"))
                        .headers("X-HMG-ROLE-API-KEY", apiKey)
                        .post("/api/admin/v1/projects/{projectKey}/members", projectKey);
        scenarioContext.setContext("responseCode", response.statusCode());
        var result = response.thenReturn().as(HashMap.class);
        if (response.statusCode() == 201) {
            scenarioContext.setContext("apiKey", result.get("apiKey"));
        }
        scenarioContext.setContext("results", result);
    }

    public boolean initialMemberChecking(String apiKey, String key, String projectKey) {
        if (StringUtils.isBlank(key)) {
            return true;
        }
        getMemberByKey(key, apiKey, projectKey);
        if (!scenarioContext.getContext("responseCode").equals(200)) {
            return true;
        }
        Response response =
                request()
                        .log()
                        .all()
                        .contentType(ContentType.JSON)
                        .headers("X-HMG-ROLE-API-KEY", apiKey)
                        .delete(
                                "/api/admin/v1/projects/{projectKey}/members/{memberKey}",
                                projectKey,
                                key);
        return ((Integer) response.statusCode()).equals(204);
    }

    private void getMemberByKey(String key, String apiKey, String projectKey) {
        Response response =
                request()
                        .log()
                        .all()
                        .contentType(ContentType.JSON)
                        .headers("X-HMG-ROLE-API-KEY", apiKey)
                        .get(
                                "/api/admin/v1/projects/{projectKey}/members/{memberKey}",
                                projectKey,
                                key);
        scenarioContext.setContext("responseCode", response.statusCode());
        var result = response.thenReturn().as(HashMap.class);
        scenarioContext.setContext("results", result);
    }
}
